development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://localhost:9292/faye"
  secret_token: "04b88f3fcd1e259e3101a5a2ac27544da2920ffdc1ee3a936c0d56e93202983b"
  signature_expiration: 3600 # one hour
